"use client";

import { useState, useEffect, useRef, Suspense } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { streamChat, type ChatMessage } from "@/lib/api";
import Sidebar from "@/components/Sidebar";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

const SUGGESTED_PROMPTS = [
  "Explain the ii-V-I progression",
  "What's the difference between major and minor?",
  "How do modes work?",
  "What makes a chord sound jazzy?",
];

function formatTime(date: Date) {
  return date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

// ── Export helper ─────────────────────────────────────────────────────────────
function buildExportHTML(messages: ChatMessage[], level: string, coveredTopics: string[], sessionStart: string) {
  const rows = messages.map((m) => {
    const label = m.role === "user" ? "You" : "Attune";
    const bg = m.role === "user" ? "#eef2ff" : "#ffffff";
    const border = m.role === "user" ? "#c7d2fe" : "#e5e7eb";
    const html = m.content
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/\*(.+?)\*/g, "<em>$1</em>")
      .replace(/`(.+?)`/g, "<code style='background:#eef2ff;padding:1px 5px;border-radius:3px'>$1</code>")
      .replace(/\n/g, "<br/>");
    return `<div style="margin-bottom:16px;padding:14px 18px;border-radius:10px;background:${bg};border:1px solid ${border}">
      <div style="font-size:10px;font-weight:700;color:#4f46e5;text-transform:uppercase;letter-spacing:0.08em;margin-bottom:6px">${label}</div>
      <div style="font-size:14px;line-height:1.75;color:#111827">${html}</div>
    </div>`;
  }).join("");

  const topicPills = coveredTopics.length
    ? coveredTopics.map(t => `<span style="display:inline-block;margin:2px 4px 2px 0;padding:2px 10px;border-radius:12px;background:#eef2ff;color:#4338ca;font-size:12px;font-weight:600">${t}</span>`).join("")
    : '<span style="color:#9ca3af;font-size:13px">None yet</span>';

  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/>
  <title>Attune Session — ${sessionStart}</title>
  <style>body{font-family:system-ui,sans-serif;margin:0;background:#f9fafb}.page{max-width:720px;margin:0 auto;padding:40px 24px}@media print{body{background:white}.page{padding:20px}}</style>
  </head><body><div class="page">
  <div style="border-bottom:2px solid #4f46e5;padding-bottom:20px;margin-bottom:28px">
    <div style="display:flex;align-items:center;gap:10px;margin-bottom:6px">
      <span style="font-size:24px">𝄞</span>
      <span style="font-size:20px;font-weight:700;color:#111827">Attune</span>
      <span style="font-size:11px;font-weight:600;background:#eef2ff;color:#4338ca;padding:2px 10px;border-radius:12px;text-transform:capitalize">${level}</span>
    </div>
    <div style="font-size:12px;color:#6b7280">Exported ${new Date().toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric"})}</div>
    <div style="margin-top:12px"><div style="font-size:10px;font-weight:700;color:#6b7280;text-transform:uppercase;letter-spacing:0.08em;margin-bottom:6px">Topics Covered</div>${topicPills}</div>
  </div>
  ${rows}
  <div style="margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af;text-align:center">Generated by Attune · Powered by Claude</div>
  </div></body></html>`;
}

function downloadHTML(html: string, filename: string) {
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

// ── Chat ─────────────────────────────────────────────────────────────────────
function ChatContent() {
  const searchParams = useSearchParams();
  const router = useRouter();

  const sessionIdParam = searchParams.get("session");
  const levelParam     = searchParams.get("level") ?? "beginner";
  const introParam     = searchParams.get("intro");

  const [sessionId, setSessionId]         = useState(sessionIdParam ?? "");
  const [level, setLevel]                 = useState(levelParam);
  const [messages, setMessages]           = useState<ChatMessage[]>([]);
  const [input, setInput]                 = useState("");
  const [streaming, setStreaming]         = useState(false);
  const [loading, setLoading]             = useState(true);
  const [sending, setSending]             = useState(false);
  const [error, setError]                 = useState<string | null>(null);
  const [sidebarOpen, setSidebarOpen]     = useState(false);
  const [sessionStart]                    = useState(() => formatTime(new Date()));
  const [coveredTopics, setCoveredTopics] = useState<string[]>([]);
  const [practiceMode, setPracticeMode]   = useState(false);
  const [copyToast, setCopyToast]         = useState(false);

  const bottomRef = useRef<HTMLDivElement>(null);
  const inputRef  = useRef<HTMLTextAreaElement>(null);

  // ── Rehydrate ───────────────────────────────────────────────────────────
  useEffect(() => {
    async function init() {
      let sid = sessionIdParam;
      let lvl = levelParam;
      if (!sid) {
        sid = localStorage.getItem("attune_session_id") ?? "";
        lvl = localStorage.getItem("attune_skill_level") ?? "beginner";
      }
      if (!sid) { router.replace("/"); return; }

      setSessionId(sid);
      setLevel(lvl);
      localStorage.setItem("attune_session_id", sid);
      localStorage.setItem("attune_skill_level", lvl);

      try {
        const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/tutor/session/${sid}/messages`);
        if (res.ok) {
          const data = await res.json();
          if (data.messages?.length > 0) {
            setMessages(data.messages);
            if (data.topics_covered?.length) setCoveredTopics(data.topics_covered);
            setLoading(false);
            return;
          }
        }
      } catch {}

      const intro = introParam ? decodeURIComponent(introParam) : "Welcome to Attune! What would you like to learn today?";
      setMessages([{ role: "assistant", content: intro }]);
      setLoading(false);
    }
    init();
  }, []);

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages]);

  useEffect(() => {
    const ta = inputRef.current;
    if (ta) { ta.style.height = "auto"; ta.style.height = `${Math.min(ta.scrollHeight, 128)}px`; }
  }, [input]);

  // ── Send ────────────────────────────────────────────────────────────────
  async function sendMessage(text?: string) {
    const msg = (text ?? input).trim();
    if (!msg || streaming || !sessionId) return;

    setInput("");
    setError(null);
    setSending(true);
    setStreaming(true);
    setSidebarOpen(false);

    setMessages(prev => [...prev, { role: "user", content: msg }, { role: "assistant", content: "" }]);

    await streamChat(
      sessionId, msg,
      practiceMode ? "practice" : "tutor",
      (chunk) => {
        setSending(false);
        setMessages(prev => {
          const updated = [...prev];
          updated[updated.length - 1] = { role: "assistant", content: updated[updated.length - 1].content + chunk };
          return updated;
        });
      },
      ({ topicsCovered }) => {
        setSending(false);
        setStreaming(false);
        if (topicsCovered.length) setCoveredTopics(topicsCovered);
      },
      (err) => {
        setSending(false);
        setStreaming(false);
        setError(err);
        setMessages(p => p.slice(0, -1));
      }
    );
  }

  function handleKeyDown(e: React.KeyboardEvent) {
    if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendMessage(); }
  }

  function startNewSession() {
    localStorage.removeItem("attune_session_id");
    localStorage.removeItem("attune_skill_level");
    router.push("/");
  }

  function togglePractice() {
    setPracticeMode(p => {
      const next = !p;
      if (next) {
        const kickoff = coveredTopics.length
          ? `Let's practice! I've been studying: ${coveredTopics.join(", ")}.`
          : "Let's practice some music theory!";
        setTimeout(() => sendMessage(kickoff), 100);
      }
      return next;
    });
  }

  function handleExport() {
    downloadHTML(buildExportHTML(messages, level, coveredTopics, sessionStart),
      `attune-session-${new Date().toISOString().slice(0, 10)}.html`);
  }

  function handleShare() {
    navigator.clipboard.writeText(window.location.href).then(() => {
      setCopyToast(true);
      setTimeout(() => setCopyToast(false), 2500);
    });
  }

  const userMessages = messages.filter(m => m.role === "user").length;

  // ── Loading ─────────────────────────────────────────────────────────────
  if (loading) {
    return (
      <div className="flex h-screen items-center justify-center bg-background">
        <div className="text-center space-y-3">
          <div className="text-4xl">𝄞</div>
          <p className="text-sm text-muted-foreground">Loading session…</p>
        </div>
      </div>
    );
  }

  // ── Render ──────────────────────────────────────────────────────────────
  return (
    <div className="flex h-screen w-screen overflow-hidden bg-background">

      {/* ── Desktop sidebar ────────────────────────────────────────────── */}
      <div className="hidden md:flex shrink-0">
        <Sidebar
          level={level}
          onTopicSelect={sendMessage}
          onNewSession={startNewSession}
          onPractice={togglePractice}
          practiceMode={practiceMode}
          coveredTopics={coveredTopics}
          sessionStart={sessionStart}
          messageCount={userMessages}
        />
      </div>

      {/* ── Mobile slide-over ──────────────────────────────────────────── */}
      {sidebarOpen && (
        <div className="fixed inset-0 z-50 flex md:hidden">
          <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setSidebarOpen(false)} />
          <div className="relative z-10 flex animate-fade-in">
            <Sidebar
              level={level}
              onTopicSelect={p => { sendMessage(p); setSidebarOpen(false); }}
              onNewSession={startNewSession}
              onPractice={() => { togglePractice(); setSidebarOpen(false); }}
              practiceMode={practiceMode}
              coveredTopics={coveredTopics}
              sessionStart={sessionStart}
              messageCount={userMessages}
              onClose={() => setSidebarOpen(false)}
            />
          </div>
        </div>
      )}

      {/* ── Main panel ─────────────────────────────────────────────────── */}
      <div className="flex flex-col flex-1 min-w-0 overflow-hidden">

        {/* Top bar */}
        <header className="flex items-center gap-3 px-4 md:px-5 h-14 border-b border-border shrink-0 bg-card/50 backdrop-blur-sm">
          {/* Hamburger — mobile */}
          <button
            onClick={() => setSidebarOpen(true)}
            className="md:hidden text-muted-foreground hover:text-foreground transition-colors p-1"
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="3" y1="6" x2="21" y2="6" />
              <line x1="3" y1="12" x2="21" y2="12" />
              <line x1="3" y1="18" x2="21" y2="18" />
            </svg>
          </button>

          {/* Mobile logo */}
          <div className="flex md:hidden items-center gap-2">
            <span className="text-lg text-primary">𝄞</span>
            <span className="font-semibold text-sm text-foreground">Attune</span>
          </div>

          {/* Breadcrumb — desktop */}
          <div className="hidden md:flex items-center gap-2 text-sm text-muted-foreground">
            {practiceMode ? (
              <>
                <span className="font-semibold text-accent-foreground">Practice Mode</span>
                <Badge variant="default" className="text-[10px]">Quiz</Badge>
              </>
            ) : (
              <>
                <span>Session</span>
                <span className="text-border">/</span>
                <span className="text-foreground/70">
                  {userMessages === 0 ? "Just started" : `${userMessages} exchange${userMessages !== 1 ? "s" : ""}`}
                </span>
              </>
            )}
          </div>

          {/* Right controls */}
          <div className="ml-auto flex items-center gap-2">
            {streaming && (
              <div className="flex items-center gap-1.5 text-xs text-primary">
                <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse" />
                Thinking
              </div>
            )}

            {/* Share */}
            <div className="relative">
              <Button
                variant="ghost"
                size="sm"
                onClick={handleShare}
                className="gap-1.5 text-xs text-muted-foreground"
              >
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/>
                  <polyline points="16 6 12 2 8 6"/><line x1="12" y1="2" x2="12" y2="15"/>
                </svg>
                <span className="hidden sm:inline">Share</span>
              </Button>
              {copyToast && (
                <div className="absolute top-full right-0 mt-1.5 bg-card border border-border rounded-lg px-3 py-1.5 text-xs text-accent-foreground whitespace-nowrap z-10 shadow-lg animate-fade-in">
                  ✓ Link copied!
                </div>
              )}
            </div>

            {/* Export */}
            <Button
              variant="ghost"
              size="sm"
              onClick={handleExport}
              disabled={messages.length < 2}
              className="gap-1.5 text-xs text-muted-foreground"
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                <polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
              </svg>
              <span className="hidden sm:inline">Export</span>
            </Button>
          </div>
        </header>

        {/* Practice banner */}
        {practiceMode && (
          <div className="flex items-center justify-between px-5 py-2 bg-primary/8 border-b border-primary/20 shrink-0">
            <div className="flex items-center gap-2">
              <span className="text-primary text-xs">🎯</span>
              <span className="text-xs text-accent-foreground">
                Practice Mode — answer in your own words, Attune will evaluate you.
              </span>
            </div>
            <button
              onClick={() => setPracticeMode(false)}
              className="text-xs text-primary hover:text-accent-foreground transition-colors"
            >
              Exit
            </button>
          </div>
        )}

        {/* Messages */}
        <div className="flex-1 overflow-y-auto">
          <div className="max-w-2xl mx-auto px-4 md:px-6 py-6 flex flex-col gap-5">

            {messages.map((msg, i) => (
              <div
                key={i}
                className={cn("flex gap-3 items-start", msg.role === "user" && "flex-row-reverse")}
              >
                {/* Avatar */}
                <div className={cn(
                  "w-7 h-7 rounded-full shrink-0 flex items-center justify-center text-xs mt-0.5",
                  msg.role === "assistant"
                    ? practiceMode
                      ? "bg-primary/20 border border-primary/30 text-primary"
                      : "bg-primary/15 border border-primary/25 text-primary"
                    : "bg-secondary border border-border text-muted-foreground font-semibold"
                )}>
                  {msg.role === "assistant" ? (practiceMode ? "?" : "𝄞") : "S"}
                </div>

                {/* Bubble */}
                <div className="max-w-[82%]">
                  {msg.role === "user" ? (
                    <div className="bg-primary text-primary-foreground rounded-2xl rounded-tr-sm px-4 py-2.5 text-sm leading-relaxed">
                      {msg.content}
                    </div>
                  ) : (
                    <div className={cn(
                      "rounded-2xl rounded-tl-sm px-4 py-3 border",
                      practiceMode
                        ? "bg-card border-primary/20"
                        : "bg-card border-border"
                    )}>
                      {i === messages.length - 1 && sending ? (
                        <div className="flex gap-1.5 py-1">
                          {[0, 150, 300].map(delay => (
                            <span
                              key={delay}
                              className="w-1.5 h-1.5 rounded-full bg-primary animate-bounce-dot"
                              style={{ animationDelay: `${delay}ms` }}
                            />
                          ))}
                        </div>
                      ) : (
                        <div className="prose-attune text-sm text-foreground">
                          <ReactMarkdown remarkPlugins={[remarkGfm]}>
                            {msg.content}
                          </ReactMarkdown>
                          {i === messages.length - 1 && streaming && !sending && (
                            <span className="inline-block w-0.5 h-4 bg-primary animate-pulse ml-0.5 align-middle" />
                          )}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              </div>
            ))}

            {/* Suggested prompts */}
            {messages.length === 1 && !streaming && (
              <div className="pl-10">
                <p className="text-xs text-muted-foreground mb-2">Try asking…</p>
                <div className="flex flex-wrap gap-2">
                  {SUGGESTED_PROMPTS.map(p => (
                    <button
                      key={p}
                      onClick={() => sendMessage(p)}
                      className="text-xs px-3 py-1.5 rounded-full border border-border text-muted-foreground hover:text-foreground hover:border-primary/40 hover:bg-secondary transition-all"
                    >
                      {p}
                    </button>
                  ))}
                </div>
              </div>
            )}

            <div ref={bottomRef} />
          </div>
        </div>

        {/* Error */}
        {error && (
          <div className="mx-4 mb-2 px-4 py-2.5 rounded-lg bg-red-500/10 border border-red-500/20 text-red-400 text-sm">
            {error}
          </div>
        )}

        {/* Input area */}
        <div className="border-t border-border px-4 md:px-6 py-4 shrink-0 bg-card/30">
          <div className="max-w-2xl mx-auto">
            <div className={cn(
              "flex items-end gap-2.5 px-4 py-3 rounded-xl border bg-card transition-colors",
              practiceMode ? "border-primary/30 focus-within:border-primary/60" : "border-border focus-within:border-primary/40"
            )}>
              <textarea
                ref={inputRef}
                value={input}
                onChange={e => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder={practiceMode ? "Type your answer…" : "Ask about chords, scales, harmony, jazz…"}
                disabled={streaming}
                rows={1}
                className="flex-1 bg-transparent border-none outline-none resize-none text-foreground text-sm leading-6 min-h-6 max-h-32 placeholder:text-muted-foreground/60 disabled:opacity-60"
              />
              <button
                onClick={() => sendMessage()}
                disabled={!input.trim() || streaming}
                className={cn(
                  "w-8 h-8 rounded-lg shrink-0 flex items-center justify-center transition-all",
                  input.trim() && !streaming
                    ? "bg-primary text-primary-foreground hover:bg-primary/90 cursor-pointer"
                    : "bg-secondary text-muted-foreground cursor-not-allowed"
                )}
              >
                {streaming ? (
                  <span className="w-3 h-3 border-2 border-muted-foreground/30 border-t-muted-foreground rounded-full animate-spin" />
                ) : (
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <line x1="22" y1="2" x2="11" y2="13" />
                    <polygon points="22 2 15 22 11 13 2 9 22 2" />
                  </svg>
                )}
              </button>
            </div>
            <p className="text-center text-muted-foreground/40 text-[11px] mt-2">
              Enter to send · Shift + Enter for new line
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function ChatPage() {
  return <Suspense><ChatContent /></Suspense>;
}
